openapi: 3.0.3
info:
  title: Q&A Service API
  description: API сервис для вопросов и ответов
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /auth/register:
    post:
      summary: Регистрация нового пользователя
      operationId: registerUser
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './models/register-request.yaml'
      responses:
        '201':
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                $ref: './models/user.yaml'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /auth/login:
    post:
      summary: Логин пользователя
      operationId: loginUser
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './models/login-request.yaml'
      responses:
        '200':
          description: Успешная авторизация
          content:
            application/json:
              schema:
                $ref: './models/auth-response.yaml'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Неверные credentials
          content:
            application/json:
              schema:
                $ref: './models/error-response.yaml'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /auth/refresh:
    post:
      summary: Обновить access token
      operationId: refreshToken
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './models/refresh-request.yaml'
      responses:
        '200':
          description: Новый access token
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Истёкший или невалидный refresh token
          content:
            application/json:
              schema:
                $ref: './models/error-response.yaml'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /questions/:
    get:
      summary: Получить список всех вопросов
      operationId: listQuestions
      tags:
        - Questions
      responses:
        '200':
          description: Список вопросов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './models/question.yaml'
        '500':
          $ref: '#/components/responses/InternalServerError'
    
    post:
      summary: Создать новый вопрос
      operationId: createQuestion
      tags:
        - Questions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './models/create-question-request.yaml'
      responses:
        '201':
          description: Вопрос создан
          content:
            application/json:
              schema:
                $ref: './models/question.yaml'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /questions/{id}:
    get:
      summary: Получить вопрос и все ответы на него
      operationId: getQuestion
      tags:
        - Questions
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: uint
      responses:
        '200':
          description: Вопрос с ответами
          content:
            application/json:
              schema:
                $ref: './models/question-with-answers.yaml'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    
    delete:
      summary: Удалить вопрос (вместе с ответами)
      operationId: deleteQuestion
      tags:
        - Questions
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: uint
      responses:
        '204':
          description: Вопрос удалён
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /questions/{id}/answers/:
    post:
      summary: Добавить ответ к вопросу (требует авторизацию)
      operationId: createAnswer
      tags:
        - Answers
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: uint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: Текст ответа (user_id заполняется автоматически)
              required:
                - text
      responses:
        '201':
          description: Ответ создан
          content:
            application/json:
              schema:
                $ref: './models/answer.yaml'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Требуется авторизация
          content:
            application/json:
              schema:
                $ref: './models/error-response.yaml'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /answers/{id}:
    get:
      summary: Получить конкретный ответ
      operationId: getAnswer
      tags:
        - Answers
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: uint
      responses:
        '200':
          description: Ответ найден
          content:
            application/json:
              schema:
                $ref: './models/answer.yaml'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    
    delete:
      summary: Удалить ответ
      operationId: deleteAnswer
      tags:
        - Answers
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: uint
      responses:
        '204':
          description: Ответ удалён
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /health:
    get:
      summary: Health check
      operationId: healthCheck
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            text/plain:
              schema:
                type: string
                example: OK

components:
  securitySchemes:
      BearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
        description: Используйте access token из /auth/login

  responses:
    BadRequest:
      description: Некорректные входные данные
      content:
        application/json:
          schema:
            $ref: './models/error-response.yaml'
    
    NotFound:
      description: Ресурс не найден
      content:
        application/json:
          schema:
            $ref: './models/error-response.yaml'
    
    InternalServerError:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: './models/error-response.yaml'